apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: ocp4
  namespace: ocp4
spec:
  clusterName: ocp4
  baseDomain: example.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: ocp4
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          agentclusterinstalls.extensions.hive.openshift.io/location: Factory
  pullSecretRef:
    name: assisted-deployment-pull-secret
