---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp4-nmstate-ocp4-master-1
  namespace: ocp4
  labels:
    cluster-name: ocp4-nmstate
    agent-install.openshift.io/role: master
    cluster-resource: ocp4-master-1
spec:
  config:
    interfaces:
    - name: bond0
      state: up
      type: bond
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '140'
        port:
        - enp1s0
        - enp2s0
      ipv4:
        dhcp: false
        enabled: true
    - name: bond0.1924
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 1924
      ipv4:
        address:
        - ip: 192.168.70.21
          prefix-length: 23
        dhcp: false
        enabled: true
    dns-resolver:
      config:
        search:
        - example.com
        server:
        - 192.168.122.161
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.70.1
        next-hop-interface: bond0.1924
        table-id: 254
  interfaces:
  - name: enp1s0
    macAddress: 52:54:00:19:04:74
  - name: enp2s0
    macAddress: 52:54:00:27:dd:41
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp4-nmstate-ocp4-master-2
  namespace: ocp4
  labels:
    cluster-name: ocp4-nmstate
    agent-install.openshift.io/role: master
    cluster-resource: ocp4-master-2
spec:
  config:
    interfaces:
    - name: bond0
      state: up
      type: bond
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '140'
        port:
        - enp1s0
        - enp2s0
      ipv4:
        dhcp: false
        enabled: true
    - name: bond0.1924
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 1924
      ipv4:
        address:
        - ip: 192.168.70.22
          prefix-length: 23
        dhcp: false
        enabled: true
    dns-resolver:
      config:
        search:
        - example.com
        server:
        - 192.168.122.161
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.70.1
        next-hop-interface: bond0.1924
        table-id: 254
  interfaces:
  - name: enp1s0
    macAddress: 52:54:00:6f:25:ec
  - name: enp2s0
    macAddress: 52:54:00:2f:52:b3
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp4-nmstate-ocp4-master-3
  namespace: ocp4
  labels:
    cluster-name: ocp4-nmstate
    agent-install.openshift.io/role: master
    cluster-resource: ocp4-master-3
spec:
  config:
    interfaces:
    - name: bond0
      state: up
      type: bond
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '140'
        port:
        - enp1s0
        - enp2s0
      ipv4:
        dhcp: false
        enabled: true
    - name: bond0.1924
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 1924
      ipv4:
        address:
        - ip: 192.168.70.23
          prefix-length: 23
        dhcp: false
        enabled: true
    dns-resolver:
      config:
        search:
        - example.com
        server:
        - 192.168.122.161
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.70.1
        next-hop-interface: bond0.1924
        table-id: 254
  interfaces:
  - name: enp1s0
    macAddress: 52:54:00:3d:e5:d8
  - name: enp2s0
    macAddress: 52:54:00:7b:4c:b9
