apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: raleigh-factory
  namespace: raleigh-factory
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: Factory
  annotations:
    agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
spec:
  clusterDeploymentRef:
    name: raleigh-factory
  imageSetRef:
    name: img4.17.17-x86-64-appsub
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
    machineNetwork:
    - cidr: 192.168.62.0/24
  provisionRequirements:
    controlPlaneAgents: 3
  sshPublicKey: ssh-rsa CHANGEME
